export default {
  home: 'Home',
  login: 'Login',
  guestHome: 'GuestHome',
  guestAdd: 'GuestAdd',
  loading: 'Loading',
  setings: 'Settings',
  newSighting: 'NewSighting',
  newSightings: 'newSighting',
  viewSighting: 'View Sighting',
  profile: 'Profile',
  notifications: 'Notifications',
  selection: 'Selection',
  localSigthing: 'LocalSighting',
};
