export default {
  'site.custom.customFieldCategories': {
    id: 'site.custom.customFieldCategories',
    value: [
      {
        timeCreated: 1602027605148,
        label: 'DNA samples',
        id: '1be9eb32-9853-4c24-91f3-4c4d296d31a6',
        type: 'Individual',
      },
      {
        timeCreated: 1602027611999,
        label: 'Safari information',
        id: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
        type: 'Sighting',
      },
      {
        timeCreated: 1602871317750,
        id: 'ba6d440c-00e2-457a-8221-348ba94af716',
        label: 'DRAGNET',
        type: 'Encounter',
      },
      {
        timeCreated: 1603848541688,
        id: '661661cd-a017-4796-ac4b-16a40b869daf',
        label: 'Left Identifier ~',
        type: 'Individual',
      },
      {
        timeCreated: 1605564056371,
        id: 'b9e0118e-000d-4933-8876-ef06af59d159',
        label: 'testind',
        type: 'Individual',
      },
    ],
    version: 1606695633876,
  },
  'site.look.lightBackgroundLogo': {
    valueNotSet: true,
    id: 'site.look.lightBackgroundLogo',
    message: {
      key: 'configuration_no_value',
    },
    value: null,
    version: 1606695633869,
  },
  'site.links.facebookLink': {
    id: 'site.links.facebookLink',
    value: 'https://www.facebook.com/marketplace/portland/furniture',
    version: 1606695633872,
  },
  'site.private': {
    id: 'site.private',
    value: true,
    version: 1606695633868,
  },
  'site.links.instagramLink': {
    id: 'site.links.instagramLink',
    value: 'http://localhost:5000/admin/settings',
    version: 1606695633873,
  },
  'site.general.exploreTagline': {
    id: 'site.general.exploreTagline',
    value: 'do stuff',
    version: 1606695633870,
  },
  'site.look.splashVideo': {
    valueNotSet: true,
    id: 'site.look.splashVideo',
    message: {
      key: 'configuration_no_value',
    },
    value: null,
    version: 1606695633874,
  },
  'site.general.tagline': {
    id: 'site.general.tagline',
    value: 'Welcome to Flukebook',
    version: 1606695633870,
  },
  'site.needsSetup': {
    usingDefault: true,
    valueNotSet: true,
    id: 'site.needsSetup',
    value: true,
    version: 1606695633867,
  },
  'site.custom.customFields.MarkedIndividual': {
    id: 'site.custom.customFields.MarkedIndividual',
    value: {
      definitions: [
        {
          schema: {
            description: 'date input',
            label: 'Date Input',
            category: '1be9eb32-9853-4c24-91f3-4c4d296d31a6',
          },
          displayType: 'date',
          name: 'DATE',
          multiple: false,
          className: 'org.ecocean.MarkedIndividual',
          id: 'c32e690c-e308-4362-82d5-bc97579e0c7f',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'daterange',
            description: 'Snarkin about',
            label: 'Range of Dates',
            category: '1be9eb32-9853-4c24-91f3-4c4d296d31a6',
          },
          name: 'daterange',
          multiple: true,
          timeCreated: 1602869336242,
          className: 'org.ecocean.MarkedIndividual',
          id: '165c3695-8eee-4a60-a9e9-eba4dacba4d0',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'select',
            description: '',
            label: 'jorbuzzy',
            choices: [
              {
                label: 'hark',
                id: '55dd5bc4-a856-499f-bfd2-8041a3925c6b',
                value: 'hark',
              },
              {
                label: 'do not hark',
                id: 'e50a6342-8da5-41d4-a1d2-0c101bfa8c74',
                value: 'do not hark',
              },
            ],
            category: '661661cd-a017-4796-ac4b-16a40b869daf',
          },
          name: 'jorbuz',
          multiple: false,
          options: ['hark', 'do not hark'],
          timeCreated: 1597264432405,
          className: 'org.ecocean.MarkedIndividual',
          id: 'fa4907e5-681e-46a8-9980-85d32cd746c4',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'string',
            description: 'wb-1014 test',
            label: 'testind test',
            category: 'b9e0118e-000d-4933-8876-ef06af59d159',
          },
          name: 'testind_test_field',
          multiple: false,
          timeCreated: 1605564095215,
          className: 'org.ecocean.MarkedIndividual',
          id: '1b62470c-890e-4665-8153-6ebefce10d28',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'feetmeters',
            description: 'feet meters',
            label: 'Feet meeters',
            category: 'b9e0118e-000d-4933-8876-ef06af59d159',
          },
          name: 'feet_meters',
          multiple: false,
          timeCreated: 1605564095215,
          className: 'org.ecocean.MarkedIndividual',
          id: '1b62470c-890e-4665-8153-6ebefce10d189',
          type: 'double',
          required: false,
        },
      ],
    },
    version: 1606695633877,
  },
  'site.general.testimonialCitation': {
    id: 'site.general.testimonialCitation',
    value: 'Joe Schmutz, farmer',
    version: 1606695633872,
  },
  'site.custom.customFields.Encounter': {
    id: 'site.custom.customFields.Encounter',
    value: {
      definitions: [
        {
          schema: {
            displayType: 'longstring',
            description: 'schluuurp',
            label: 'Berry Types',
          },
          name: 'berryTypes',
          multiple: true,
          timeCreated: 1602869045041,
          className: 'org.ecocean.Encounter',
          id: '12459f79-5e9a-45ad-b914-0073881b8b55',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'daterange',
            description: 'Snarkin about',
            label: 'Date Range',
          },
          name: 'daterange',
          multiple: true,
          timeCreated: 1602869336242,
          className: 'org.ecocean.Encounter',
          id: '165c3695-8eee-4a60-a9e9-eba4dacba4d0',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'longstring',
            description: 'schluuurp',
            label: 'testoprime',
          },
          name: 'testo',
          multiple: false,
          timeCreated: 1602869045041,
          className: 'org.ecocean.Encounter',
          id: '48259ec8-0307-4c55-b181-ef721b8f203b',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'locationIds',
            description: 'schluuurp',
            label: 'Location ID',
          },
          name: 'locationID',
          multiple: false,
          timeCreated: 1602869045041,
          className: 'org.ecocean.Encounter',
          id: '48259ec8-0307-4c55-b181-ef721b8f2123',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'individual',
            description: 'indiua',
            label: 'Individual',
          },
          name: 'individual',
          multiple: false,
          timeCreated: 1602869045041,
          className: 'org.ecocean.Encounter',
          id: '48259ec8-0307-4c55-b181-ef721b8f2908nuk',
          type: 'string',
          required: false,
        },
      ],
    },
    version: 1606695633877,
  },
  'site.general.description': {
    id: 'site.general.description',
    value:
      'The elusive Wilderbeest has never been seen before. But if it is, this website will be here waiting. ',
    version: 1606695633871,
  },
  'site.name': {
    id: 'site.name',
    value: 'ဤမျှလောက်များစွာသောတိရိစ္ဆာန်များ',
    version: 1606695633867,
  },
  'site.general.taglineSubtitle': {
    id: 'site.general.taglineSubtitle',
    value: 'Send us your photos of the elusive Wilderbeest.',
    version: 1606695633870,
  },
  'site.general.testimonial': {
    id: 'site.general.testimonial',
    value:
      "I didn't see the Wilderbeest, but I heard it. I've never been more sure of anything in my life.",
    version: 1606695633871,
  },
  'site.look.darkBackgroundLogo': {
    valueNotSet: true,
    id: 'site.look.darkBackgroundLogo',
    message: {
      key: 'configuration_no_value',
    },
    value: null,
    version: 1606695633869,
  },
  'site.links.twitterLink': {
    id: 'site.links.twitterLink',
    value: '',
    version: 1606695633874,
  },
  'site.look.footerLogo': {
    valueNotSet: true,
    id: 'site.look.footerLogo',
    message: {
      key: 'configuration_no_value',
    },
    value: null,
    version: 1606695633875,
  },
  'site.custom.regions': {
    id: 'site.custom.regions',
    value: {
      locationID: [
        {
          locationID: [
            {
              locationID: [
                {
                  locationID: [],
                  name: '22fas',
                  id: '740ec3d1-40b3-4338-8c1f-3ea73b3af893',
                },
              ],
              name: 'Lewa',
              timeZone: 'Africa/Nairobi',
              defaultLatitude: 0.2,
              defaultLongitude: 37.41,
              id: 'Lewa',
            },
            {
              locationID: [],
              name: 'Ol Pejetera',
              timeZone: 'Africa/Nairobi',
              defaultLatitude: 0,
              defaultLongitude: 37,
              id: 'Ol Pejeta',
            },
          ],
          name: 'Niger',
          timeZone: 'Africa/Niamey',
          defaultLatitude: 17.638133,
          defaultLongitude: 9.766846,
          id: 'Niger',
        },
        {
          locationID: [],
          name: 'Chad',
          timeZone: 'Africa/Ndjamena',
          defaultLatitude: 17.638133,
          defaultLongitude: 9.766846,
          id: 'Chad',
        },
        {
          locationID: [],
          name: 'Namibia',
          timeZone: 'Africa/Windhoek',
          defaultLatitude: -22,
          defaultLongitude: 17,
          id: 'Namibia',
        },
      ],
      description: 'we require a root-level node here fwiw',
    },
    version: 1606695633875,
  },
  'site.custom.customFields.Occurrence': {
    id: 'site.custom.customFields.Occurrence',
    value: {
      definitions: [
        {
          schema: {
            displayType: 'feetmeters',
            description: 'AWEFAWEF',
            label: 'Abcd',
            category: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
          },
          name: 'Abcd',
          multiple: false,
          timeCreated: 1604947740534,
          className: 'org.ecocean.Occurrence',
          id: 'd9dcd12b-e180-477c-8488-3df8a3f9d9d8',
          type: 'double',
          required: false,
        },
        {
          schema: {
            displayType: 'longstring',
            category: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
          },
          displayType: 'magicFrontEnd',
          multiple: false,
          options: ['dog', 'cat'],
          name: 'Magicness',
          className: 'org.ecocean.Occurrence',
          id: 'd675a8a0-d499-4651-81d1-5c233df4c6dd',
          type: 'string',
        },
        {
          schema: {
            displayType: 'latlong',
            category: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
            label: 'Multi Select',
            choices: [
              {
                label: 'a',
                id: '55dd5bc4-a856-499f-bfd2-8041a3925c6b',
                value: 'a',
              },
              {
                label: 'b',
                id: 'e50a6342-8da5-41d4-a1d2-0c101bfa8c74',
                value: 'b',
              },
              {
                label: 'c',
                id: 'e50a6342-8da5-0c101bfa8c74',
                value: 'c',
              },
            ],
          },
          multiple: true,
          name: 'MultiSelect',
          className: 'org.ecocean.Occurrence',
          id: 'c4131e13-42dd-4eb9-ad2c-40cde2835949',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'locationIds',
            description: '',
            label: 'Location Id',
            choices: [
              {
                label: 'abc',
                id: '8f485ad9-8412-4bcc-b29a-d59e5d557a77',
                value: 'abc',
              },
              {
                label: 'def',
                id: 'c567d1c7-104a-4e22-bb11-a58cf63ba986',
                value: 'def',
              },
            ],
            category: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
          },
          name: 'dropitup',
          multiple: false,
          options: ['abc', 'def'],
          timeCreated: 1597263178160,
          className: 'org.ecocean.Occurrence',
          id: '0000045f-7b76-4eb0-885b-26a910cb5160',
          type: 'string',
          required: true,
        },
        {
          schema: {
            displayType: 'latlong',
            label: 'Lat Long',
          },
          multiple: false,
          name: 'lat long',
          className: 'org.ecocean.Occurrence',
          id: '1a701d24-83eb-4ae9-a0ca-9210b85f0c60',
          type: 'string',
          required: false,
        },
        {
          schema: {
            displayType: 'boolean',
            description: 'ABcd',
            label: 'Boolean',
            category: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
          },
          name: 'boolean',
          multiple: false,
          timeCreated: 1604947602046,
          className: 'org.ecocean.Occurrence',
          id: '391ed61f-6dd3-4390-a25e-7dda58c596fa',
          type: 'string',
          required: false,
        },
        {
          schema: {
            category: 'd52499ba-b0d3-44e1-af8a-0b72cbc300b8',
          },
          displayType: 'area',
          name: 'Area',
          multiple: false,
          className: 'org.ecocean.Occurrence',
          id: 'aaaaa8a0-d499-4651-81d1-5c233df4c6dd',
          type: 'string',
          required: false,
        },
        {
          displayType: 'file',
          name: 'File Input',
          multiple: false,
          className: 'org.ecocean.Occurrence',
          id: 'bbbba8a0-d499-4651-81d1-5c233df4c6dd',
          type: 'string',
          required: false,
        },
      ],
    },
    version: 1606695633876,
  },
  'site.look.themeColor': {
    id: 'site.look.themeColor',
    value: '#CDABFD',
    version: 1606695633868,
  },
};
