export default storage = {
  sightings: [
    {
      id: 1,
      image: require('../../assets/humpback.jpg'),
      name: 'Humpback Whale',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 2,
      image: require('../../assets/hummingbird.jpg'),
      name: 'Anna\'s Hummingbird',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 3,
      image: require('../../assets/redPanda.jpg'),
      name: 'Red Panda',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 4,
      image: require('../../assets/octopus.jpg'),
      name: 'Maldives Octopus',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 5,
      image: require('../../assets/whaleshark.jpg'),
      name: 'Whale Shark',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 6,
      image: require('../../assets/lizard.jpg'),
      name: 'Indonesian Forest Liza...',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 7,
      image: require('../../assets/elephant.jpg'),
      name: 'African Bush Elephant',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
    {
      id: 8,
      image: require('../../assets/jaguar.jpg'),
      name: 'North American Jaguar',
      date: 'September 23rd, 2019',
      synced: true,
      inProgress: false,
    },
  ],
};
