import Humpback from '../../assets/images/humpback.jpg';
import Hummingbird from '../../assets/images/hummingbird.jpg';
import RedPanda from '../../assets/images/redPanda.jpg';
import Octopus from '../../assets/images/octopus.jpg';
import WhaleShark from '../../assets/images/whaleshark.jpg';
import Lizard from '../../assets/images/lizard.jpg';
import Elephant from '../../assets/images/elephant.jpg';
import Jaguar from '../../assets/images/jaguar.jpg';

export default storage = {
  //dummy data for testing 
  sightings: [
    {
      id: 1,
      image: Humpback,
      name: 'Humpback Whale',
      date: 'September 23rd, 2019',
      species: 'Humpback Whale',
      Title: 'Humpy',
      Location: 'Portland OR ',
      Context: 'I saw it. The thing was absolutly massive bro',
      synced: true,
      inProgress: false,
    },
    {
      id: 2,
      image: Hummingbird,
      name: "Anna's Hummingbird",
      date: 'October 23rd, 2019',
      species: 'Hummingbird',
      Title: 'Humming',
      Location: 'Beaverton OR',
      Context: 'A Cute Little Bird',
      synced: true,
      inProgress: false,
    },
    {
      id: 3,
      image: RedPanda,
      name: 'Red Panda',
      date: 'September 23rd, 2019',
      species: 'Red Panda',
      Title: 'Pabu',
      Location: 'China',
      Context: 'Its that pet from LoK',
      synced: true,
      inProgress: false,
    },
    {
      id: 4,
      image: Octopus,
      name: 'Maldives Octopus',
      date: 'November 23rd, 2019',
      species: 'Octopus',
      Title: 'Tako',
      Location: 'Maldives',
      Context: 'Freaky little guy',
      synced: true,
      inProgress: false,
    },
    {
      id: 5,
      image: WhaleShark,
      name: 'Whale Shark',
      date: 'September 23rd, 2019',
      species: 'Whale Shark',
      Title: 'Whale Shark',
      Location: 'Australia',
      Context: 'Went diving, found this guy',
      synced: true,
      inProgress: false,
    },
    {
      id: 6,
      image: Lizard,
      name: 'Indonesian Forest Liza...',
      date: 'September 23rd, 2019',
      species: 'Indonesian Forest Lizard',
      Title: 'Lizard',
      Location: 'Indonesia',
      Context: 'Got lost on a hiking trail, found this guy',
      synced: true,
      inProgress: false,
    },
    {
      id: 7,
      image: Elephant,
      name: 'African Bush Elephant',
      date: 'September 23rd, 2019',
      species: 'African Bush Elephant',
      Title: 'Elephant',
      Location: 'Central Africa',
      Context: 'Big, Absoluely massive',
      synced: true,
      inProgress: false,
    },
    {
      id: 8,
      image: Jaguar,
      name: 'North American Jaguar',
      date: 'September 23rd, 2019',
      species: 'North American Jaguar',
      Title: 'Jaguar',
      Location: 'Arizona, US',
      Context: 'A scary, fast cat',
      synced: true,
      inProgress: false,
    },
  ],
};
